language: csharp
mono: none
dotnet: 5.0
os: linux
dist: focal
before_install:
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - export PYTHONNET_PYDLL="$HOME/miniconda3/lib/libpython3.6m.so"
  - wget -q https://cdn.quantconnect.com/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh
  - bash Miniconda3-4.5.12-Linux-x86_64.sh -b
  - rm -rf Miniconda3-4.5.12-Linux-x86_64.sh
  - sudo ln -s $HOME/miniconda3/lib/libpython3.6m.so /usr/lib/libpython3.6m.so
  - conda update -y python conda pip
  - conda install -y python=3.6.8
  - conda install -y numpy=1.18.1
  - conda install -y pandas=0.25.3
  - conda install -y cython=0.29.15
  - conda install -y scipy=1.4.1
  - conda install -y wrapt=1.12.1
script:
  - dotnet nuget add source $TRAVIS_BUILD_DIR/LocalPackages
  - dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 QuantConnect.Lean.sln
  - dotnet test ./Tests/bin/Release/QuantConnect.Tests.dll --filter TestCategory!=TravisExclude -- TestRunParameters.Parameter\(name=\"log-handler\", value=\"ConsoleErrorLogHandler\"\)