name: Research Regression Tests

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: quantconnect/lean:foundation
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          pip3 install papermill clr-loader

      - name: install kernel
        run: dotnet tool install --global Microsoft.dotnet-interactive --version 1.0.317502

      - name: Add dotnet tools to Path
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: activate kernel for jupyter
        run: dotnet interactive jupyter install

      - name: Build
        run: dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 QuantConnect.Lean.sln

      - name: Run Tests
        run: dotnet test ./Tests/bin/Release/QuantConnect.Tests.dll --filter TestCategory=ResearchRegressionTests -- TestRunParameters.Parameter\(name=\"log-handler\", value=\"ConsoleErrorLogHandler\"\) TestRunParameters.Parameter\(name=\"reduced-disk-size\", value=\"true\"\)
